<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?= view('exports/pdf_styles') ?>
</head>
<body>
    <div class="header">
        <h1>Pharxmaco Drugstore</h1>
        <h2>Expiry Report</h2>
        <table class="meta">
            <tr>
                <td class="meta-label">Branch</td><td><?= esc($branchName ?? 'All Branches') ?></td>
                <td class="meta-label">Status</td><td><?= esc($filterStatusLabel ?? 'All Statuses') ?></td>
            </tr>
            <tr>
                <td class="meta-label">Warning Window</td><td><?= esc($nearExpiryDays ?? 30) ?> days</td>
                <td class="meta-label">Report Date</td><td><?= esc(\App\Libraries\DisplayDate::date($today ?? null)) ?></td>
            </tr>
            <tr>
                <td class="meta-label">Generated By</td><td><?= esc($generatedBy ?? 'System User') ?></td>
                <td class="meta-label">Generated At</td><td><?= esc($generatedAt ?? '') ?></td>
            </tr>
        </table>
    </div>

    <?php if (!empty($filterNotices)): ?>
        <div class="notice"><strong>Filter note:</strong> <?= esc(implode(' ', $filterNotices)) ?></div>
    <?php endif; ?>

    <table class="summary">
        <tr>
            <td><span class="label">Total Records</span><span class="value"><?= esc($summary['total'] ?? 0) ?></span></td>
            <td><span class="label">Expired</span><span class="value"><?= esc($summary['expired'] ?? 0) ?></span></td>
            <td><span class="label">Near Expiry</span><span class="value"><?= esc($summary['near'] ?? 0) ?></span></td>
            <td><span class="label">Good</span><span class="value"><?= esc($summary['good'] ?? 0) ?></span></td>
            <td><span class="label">No Expiry Date</span><span class="value"><?= esc($summary['missing'] ?? 0) ?></span></td>
        </tr>
    </table>

    <div class="section-title">Inventory Expiry Details</div>
    <p class="section-note">Status is evaluated as of the report date. Stock quantities are in each product's recorded unit.</p>
    <table class="data">
        <thead>
            <tr>
                <th style="width:18%;">Product</th>
                <th style="width:10%;">SKU</th>
                <th style="width:13%;">Manufacturer</th>
                <th style="width:13%;">Supplier</th>
                <th style="width:12%;">Branch</th>
                <th style="width:7%;">Stock</th>
                <th style="width:13%;">Expiration Date</th>
                <th style="width:14%;">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($products)): ?>
                <?php foreach ($products as $p): ?>
                    <?php
                    $expiry = $p['expiration_date'] ?? null;
                    $status = 'No Expiry Date';
                    $statusClass = 'status-missing';
                    if (!empty($expiry)) {
                        $status = 'Good';
                        $statusClass = 'status-good';
                        if ($expiry < $today) {
                            $status = 'Expired';
                            $statusClass = 'status-expired';
                        } elseif ($expiry <= $nearDate) {
                            $status = 'Near Expiry';
                            $statusClass = 'status-near';
                        }
                    }
                    ?>
                    <tr>
                        <td><?= esc($p['product_name'] ?? '-') ?></td>
                        <td><?= esc($p['sku'] ?? '-') ?></td>
                        <td><?= esc($p['manufacturer'] ?? '-') ?></td>
                        <td><?= esc($p['supplier_name'] ?? '-') ?></td>
                        <td><?= esc($p['branch_name'] ?? '-') ?></td>
                        <td class="num"><?= esc($p['stock'] ?? 0) ?></td>
                        <td><?= esc(\App\Libraries\DisplayDate::date($expiry ?: '-')) ?></td>
                        <td class="<?= esc($statusClass) ?>"><?= esc($status) ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="8" class="empty">No expiry records matched the selected filters.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
</body>
</html>
