<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use App\Models\StockLogModel;
use Dompdf\Dompdf;
use App\Libraries\PdfFactory;

class StockLogsController extends BaseController
{
    private const ACTION_TYPES = [
        'stock_in' => 'Stock In',
        'stock_out' => 'Stock Out',
        'adjustment' => 'Adjustment',
        'expired' => 'Expired',
        'returned' => 'Returned',
    ];

    private array $filterNotices = [];

    public function index()
    {
        $model = new StockLogModel();
        $db = \Config\Database::connect();
        $filters = $this->resolveFilters($db);

        $builder = $this->stockLogBuilder($model, $filters);
        $logs = $builder
            ->orderBy('stock_logs.id', 'DESC')
            ->paginate(15);

        $branchesBuilder = $db->table('branches')
            ->where('status', 'active')
            ->orderBy('branch_name', 'ASC');

        if ($this->isCashier()) {
            $branchesBuilder->where('id', (int) $filters['branch_id']);
        }

        return view('stock_logs/index', [
            'logs' => $logs,
            'pager' => $model->pager,
            'search' => $filters['search'],
            'branches' => $branchesBuilder->get()->getResultArray(),
            'filterBranch' => $filters['branch_id'],
            'filterActionType' => $filters['action_type'],
            'dateFrom' => $filters['date_from'],
            'dateTo' => $filters['date_to'],
            'filterNotices' => array_values(array_unique($this->filterNotices)),
            'isCashier' => $this->isCashier(),
        ]);
    }

    public function exportExcel()
    {
        $db = \Config\Database::connect();
        $filters = $this->resolveFilters($db);
        $logs = $this->stockLogBuilder(new StockLogModel(), $filters)
            ->orderBy('stock_logs.id', 'DESC')
            ->get()
            ->getResultArray();

        $branchName = $this->resolveBranchName($db, $filters['branch_id']);
        $generatedAt = \App\Libraries\DisplayDate::dateTime(time());
        $generatedBy = (string) (session('full_name') ?: session('username') ?: 'System User');
        $filename = $this->buildFilename('stock_logs', $branchName, $filters, 'csv');

        $this->prepareDownloadHeaders('text/csv; charset=utf-8', $filename);

        $output = fopen('php://output', 'w');
        if ($output === false) {
            throw new \RuntimeException('Unable to open the export output stream.');
        }

        fwrite($output, "\xEF\xBB\xBF");
        $this->writeCsvRow($output, ['Pharxmaco Drugstore - Stock Logs']);
        $this->writeCsvRow($output, ['Generated By', $generatedBy]);
        $this->writeCsvRow($output, ['Generated At', $generatedAt]);
        $this->writeCsvRow($output, ['Timezone', 'Asia/Manila']);
        $this->writeCsvRow($output, ['Branch', $branchName]);
        $this->writeCsvRow($output, ['Type', $this->actionTypeLabel($filters['action_type'])]);
        $this->writeCsvRow($output, ['Date From', $filters['date_from'] !== '' ? \App\Libraries\DisplayDate::date($filters['date_from']) : 'All Dates']);
        $this->writeCsvRow($output, ['Date To', $filters['date_to'] !== '' ? \App\Libraries\DisplayDate::date($filters['date_to']) : 'All Dates']);
        $this->writeCsvRow($output, ['Search', $filters['search'] !== '' ? $filters['search'] : 'None']);
        $this->writeCsvRow($output, ['Total Records', count($logs)]);

        if (!empty($this->filterNotices)) {
            $this->writeCsvRow($output, []);
            $this->writeCsvRow($output, ['FILTER NOTES']);
            foreach (array_unique($this->filterNotices) as $notice) {
                $this->writeCsvRow($output, [$notice]);
            }
        }

        $this->writeCsvRow($output, []);
        $this->writeCsvRow($output, [
            'ID',
            'Product',
            'Branch',
            'User',
            'Action Type',
            'Quantity',
            'Previous Stock',
            'New Stock',
            'Remarks',
            'Date and Time',
        ]);

        foreach ($logs as $log) {
            $this->writeCsvRow($output, [
                (int) ($log['id'] ?? 0),
                $log['product_name'] ?? '-',
                $log['branch_name'] ?? '-',
                $log['full_name'] ?? '-',
                $this->actionTypeLabel((string) ($log['action_type'] ?? '')),
                (int) ($log['quantity'] ?? 0),
                (int) ($log['previous_stock'] ?? 0),
                (int) ($log['new_stock'] ?? 0),
                $log['remarks'] ?? '',
                $this->formatDateTime($log['created_at'] ?? null),
            ]);
        }

        fclose($output);
        exit;
    }

    public function exportPdf()
    {
        $db = \Config\Database::connect();
        $filters = $this->resolveFilters($db);
        $logs = $this->stockLogBuilder(new StockLogModel(), $filters)
            ->orderBy('stock_logs.id', 'DESC')
            ->get()
            ->getResultArray();

        $branchName = $this->resolveBranchName($db, $filters['branch_id']);
        $generatedAt = date('F j, Y \a\t g:i A');
        $generatedBy = (string) (session('full_name') ?: session('username') ?: 'System User');

        $html = view('stock_logs/pdf', [
            'logs' => $logs,
            'branchName' => $branchName,
            'dateFrom' => $filters['date_from'],
            'dateTo' => $filters['date_to'],
            'search' => $filters['search'],
            'actionTypeLabel' => $this->actionTypeLabel($filters['action_type']),
            'generatedAt' => $generatedAt,
            'generatedBy' => $generatedBy,
            'filterNotices' => array_values(array_unique($this->filterNotices)),
        ]);

        $dompdf = PdfFactory::create();
        $dompdf->loadHtml($html, 'UTF-8');
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $this->addPageNumbers($dompdf);

        $filename = $this->buildFilename('stock_logs', $branchName, $filters, 'pdf');
        $this->clearOutputBuffers();
        $dompdf->stream($filename, ['Attachment' => true]);
        exit;
    }

    private function stockLogBuilder(StockLogModel $model, array $filters)
    {
        $builder = $model
            ->select('
                stock_logs.*,
                products.product_name,
                users.full_name,
                branches.branch_name
            ')
            ->join('products', 'products.id = stock_logs.product_id', 'left')
            ->join('users', 'users.id = stock_logs.user_id', 'left')
            ->join('branches', 'branches.id = stock_logs.branch_id', 'left');

        if ($filters['search'] !== '') {
            $builder->groupStart()
                ->like('products.product_name', $filters['search'])
                ->orLike('users.full_name', $filters['search'])
                ->orLike('stock_logs.action_type', $filters['search'])
                ->orLike('stock_logs.remarks', $filters['search'])
                ->groupEnd();
        }

        if ($filters['branch_id'] !== '') {
            $builder->where('stock_logs.branch_id', (int) $filters['branch_id']);
        }

        if ($filters['action_type'] !== '') {
            $builder->where('stock_logs.action_type', $filters['action_type']);
        }

        if ($filters['date_from'] !== '') {
            $builder->where('stock_logs.created_at >=', $filters['date_from'] . ' 00:00:00');
        }

        if ($filters['date_to'] !== '') {
            $builder->where('stock_logs.created_at <=', $filters['date_to'] . ' 23:59:59');
        }

        return $builder;
    }

    private function resolveFilters($db): array
    {
        $search = $this->queryValue('search');
        $branchId = $this->queryValue('branch_id');
        $actionType = $this->queryValue('action_type');
        $dateFrom = $this->queryValue('date_from');
        $dateTo = $this->queryValue('date_to');

        if ($actionType !== '' && !array_key_exists($actionType, self::ACTION_TYPES)) {
            $this->filterNotices[] = 'The selected stock-log type was invalid and was ignored.';
            $actionType = '';
        }

        if ($this->isCashier()) {
            $assignedBranchId = (int) session('branch_id');
            $branchId = $assignedBranchId > 0 ? (string) $assignedBranchId : '0';
            if ($assignedBranchId < 1) {
                $this->filterNotices[] = 'No active branch is assigned to this cashier, so no stock logs are available.';
            }
        } elseif ($branchId !== '') {
            if (!ctype_digit($branchId) || (int) $branchId < 1) {
                $this->filterNotices[] = 'The selected branch was invalid and was ignored.';
                $branchId = '';
            } else {
                $branch = $db->table('branches')
                    ->select('id')
                    ->where('id', (int) $branchId)
                    ->where('status', 'active')
                    ->get()
                    ->getRowArray();
                if (!$branch) {
                    $this->filterNotices[] = 'The selected branch is unavailable and was ignored.';
                    $branchId = '';
                }
            }
        }

        $dateFrom = $this->normalizeDate($dateFrom, 'start');
        $dateTo = $this->normalizeDate($dateTo, 'end');

        if ($dateFrom !== '' && $dateTo !== '' && $dateFrom > $dateTo) {
            [$dateFrom, $dateTo] = [$dateTo, $dateFrom];
            $this->filterNotices[] = 'The stock-log start and end dates were reversed, so they were swapped.';
        }

        return [
            'search' => mb_substr($search, 0, 150),
            'branch_id' => $branchId,
            'action_type' => $actionType,
            'date_from' => $dateFrom,
            'date_to' => $dateTo,
        ];
    }

    private function queryValue(string $key): string
    {
        $value = $this->request->getGet($key);
        if ($value === null) {
            return '';
        }
        if (!is_scalar($value)) {
            $this->filterNotices[] = "The {$key} filter was invalid and was ignored.";
            return '';
        }
        return trim((string) $value);
    }

    private function normalizeDate(string $value, string $label): string
    {
        if ($value === '') {
            return '';
        }

        $date = \DateTimeImmutable::createFromFormat('!Y-m-d', $value);
        if ($date === false || $date->format('Y-m-d') !== $value) {
            $this->filterNotices[] = "The {$label} date was invalid and was ignored.";
            return '';
        }

        $today = date('Y-m-d');
        if ($value > $today) {
            $this->filterNotices[] = "The {$label} date was in the future and was changed to today.";
            return $today;
        }

        return $value;
    }

    private function resolveBranchName($db, string $branchId): string
    {
        if ($branchId === '') {
            return 'All Branches';
        }
        if ($branchId === '0') {
            return 'No Assigned Branch';
        }

        $branch = $db->table('branches')
            ->select('branch_name')
            ->where('id', (int) $branchId)
            ->get()
            ->getRowArray();

        return (string) ($branch['branch_name'] ?? 'Unavailable Branch');
    }

    private function actionTypeLabel(string $value): string
    {
        if ($value === '') {
            return 'All Types';
        }
        return self::ACTION_TYPES[$value] ?? ucwords(str_replace('_', ' ', $value));
    }

    private function writeCsvRow($output, array $row): void
    {
        \App\Libraries\CsvExport::writeRow($output, $row, 10);
    }

    private function prepareDownloadHeaders(string $contentType, string $filename): void
    {
        $this->clearOutputBuffers();
        header('Content-Type: ' . $contentType);
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('X-Content-Type-Options: nosniff');
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        header('Expires: 0');
    }

    private function clearOutputBuffers(): void
    {
        while (ob_get_level() > 0) {
            ob_end_clean();
        }
    }

    private function buildFilename(string $prefix, string $branchName, array $filters, string $extension): string
    {
        $branch = preg_replace('/[^A-Za-z0-9_-]+/', '_', $branchName) ?: 'all_branches';
        $from = $filters['date_from'] !== '' ? $filters['date_from'] : 'all_dates';
        $to = $filters['date_to'] !== '' ? $filters['date_to'] : 'all_dates';
        return strtolower($prefix . '_' . trim($branch, '_') . '_' . $from . '_to_' . $to . '_' . date('Ymd_His') . '.' . $extension);
    }

    private function formatDateTime($value): string
    {
        if (empty($value)) {
            return '';
        }
        return \App\Libraries\DisplayDate::dateTime($value);
    }

    private function addPageNumbers(Dompdf $dompdf): void
    {
        $canvas = $dompdf->getCanvas();
        $font = $dompdf->getFontMetrics()->getFont('DejaVu Sans', 'normal');
        $canvas->page_text(34, $canvas->get_height() - 30, 'PHARXMACO  |  Stock movement report  |  A4 landscape', $font, 8, [0.25, 0.28, 0.32]);
        $canvas->page_text(
            $canvas->get_width() - 115,
            $canvas->get_height() - 30,
            'Page {PAGE_NUM} of {PAGE_COUNT}',
            $font,
            8,
            [0.35, 0.35, 0.35]
        );
    }

    private function isCashier(): bool
    {
        return session('role') === 'cashier';
    }
}
